export const test_toots = [
  {
    "id": "109472499431799134",
    "created_at": "2022-12-07T12:56:16.979Z",
    "in_reply_to_id": null,
    "in_reply_to_account_id": null,
    "sensitive": true,
    "spoiler_text": "Content Warning",
    "visibility": "public",
    "language": "en",
    "uri": "https://ohai.social/users/cookie_mumbles/statuses/109472499431799134",
    "url": "https://ohai.social/@cookie_mumbles/109472499431799134",
    "replies_count": 0,
    "reblogs_count": 1,
    "favourites_count": 3,
    "edited_at": null,
    "content": "<p>CONTENT</p><p>(told ya)</p>",
    "reblog": null,
    "application": null,
    "account": {
      "id": "109380999955395974",
      "username": "cookie_mumbles",
      "acct": "cookie_mumbles",
      "display_name": "Cookie Mumbles",
      "locked": false,
      "bot": false,
      "discoverable": false,
      "group": false,
      "created_at": "2022-11-21T00:00:00.000Z",
      "note": "<p>Friendly cis cookie on a quest to make you chuckle</p><p>My toots -&gt; <a href=\"https://justmytoots.com/cookie_mumbles@ohai.social\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"><span class=\"invisible\">https://</span><span class=\"ellipsis\">justmytoots.com/cookie_mumbles</span><span class=\"invisible\">@ohai.social</span></a></p><p>best-of etc on twitter -&gt; <a href=\"https://linktr.ee/cookie_mumbles\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"><span class=\"invisible\">https://</span><span class=\"\">linktr.ee/cookie_mumbles</span><span class=\"invisible\"></span></a></p><p><a href=\"https://ohai.social/tags/fedi22\" class=\"mention hashtag\" rel=\"tag\">#<span>fedi22</span></a><br /><a href=\"https://ohai.social/tags/jokes\" class=\"mention hashtag\" rel=\"tag\">#<span>jokes</span></a> <a href=\"https://ohai.social/tags/fun\" class=\"mention hashtag\" rel=\"tag\">#<span>fun</span></a> <a href=\"https://ohai.social/tags/nobot\" class=\"mention hashtag\" rel=\"tag\">#<span>nobot</span></a> <a href=\"https://ohai.social/tags/joke\" class=\"mention hashtag\" rel=\"tag\">#<span>joke</span></a> <a href=\"https://ohai.social/tags/humor\" class=\"mention hashtag\" rel=\"tag\">#<span>humor</span></a> <a href=\"https://ohai.social/tags/trending\" class=\"mention hashtag\" rel=\"tag\">#<span>trending</span></a> <a href=\"https://ohai.social/tags/funny\" class=\"mention hashtag\" rel=\"tag\">#<span>funny</span></a></p>",
      "url": "https://ohai.social/@cookie_mumbles",
      "avatar": "https://files.ohai.social/accounts/avatars/109/380/999/955/395/974/original/c814d08a32d2a639.png",
      "avatar_static": "https://files.ohai.social/accounts/avatars/109/380/999/955/395/974/original/c814d08a32d2a639.png",
      "header": "https://files.ohai.social/accounts/headers/109/380/999/955/395/974/original/9c502235dd1c0795.jpeg",
      "header_static": "https://files.ohai.social/accounts/headers/109/380/999/955/395/974/original/9c502235dd1c0795.jpeg",
      "followers_count": 355,
      "following_count": 284,
      "statuses_count": 566,
      "last_status_at": "2022-12-07",
      "noindex": false,
      "emojis": [],
      "role": null,
      "fields": []
    },
    "media_attachments": [],
    "mentions": [],
    "tags": [],
    "emojis": [],
    "card": null,
    "poll": null
  },
  {
    "id": "109463245078881912",
    "created_at": "2022-12-05T21:42:46.756Z",
    "in_reply_to_id": null,
    "in_reply_to_account_id": null,
    "sensitive": false,
    "spoiler_text": "",
    "visibility": "public",
    "language": "en",
    "uri": "https://ohai.social/users/cookie_mumbles/statuses/109463245078881912",
    "url": "https://ohai.social/@cookie_mumbles/109463245078881912",
    "replies_count": 0,
    "reblogs_count": 2,
    "favourites_count": 2,
    "edited_at": null,
    "content": "<p>Shady figure: hey pssst! Wanna *opens coat revealing assortment of coke cans* Taste the Feeling?</p>",
    "reblog": null,
    "application": {
      "name": "Metatext",
      "website": "https://metabolist.org/metatext"
    },
    "account": {
      "id": "109380999955395974",
      "username": "cookie_mumbles",
      "acct": "cookie_mumbles",
      "display_name": "Cookie Mumbles",
      "locked": false,
      "bot": false,
      "discoverable": false,
      "group": false,
      "created_at": "2022-11-21T00:00:00.000Z",
      "note": "<p>Friendly cis cookie on a quest to make you chuckle</p><p>My toots -&gt; <a href=\"https://justmytoots.com/cookie_mumbles@ohai.social\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"><span class=\"invisible\">https://</span><span class=\"ellipsis\">justmytoots.com/cookie_mumbles</span><span class=\"invisible\">@ohai.social</span></a></p><p>best-of etc on twitter -&gt; <a href=\"https://linktr.ee/cookie_mumbles\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"><span class=\"invisible\">https://</span><span class=\"\">linktr.ee/cookie_mumbles</span><span class=\"invisible\"></span></a></p><p><a href=\"https://ohai.social/tags/fedi22\" class=\"mention hashtag\" rel=\"tag\">#<span>fedi22</span></a><br /><a href=\"https://ohai.social/tags/jokes\" class=\"mention hashtag\" rel=\"tag\">#<span>jokes</span></a> <a href=\"https://ohai.social/tags/fun\" class=\"mention hashtag\" rel=\"tag\">#<span>fun</span></a> <a href=\"https://ohai.social/tags/nobot\" class=\"mention hashtag\" rel=\"tag\">#<span>nobot</span></a> <a href=\"https://ohai.social/tags/joke\" class=\"mention hashtag\" rel=\"tag\">#<span>joke</span></a> <a href=\"https://ohai.social/tags/humor\" class=\"mention hashtag\" rel=\"tag\">#<span>humor</span></a> <a href=\"https://ohai.social/tags/trending\" class=\"mention hashtag\" rel=\"tag\">#<span>trending</span></a> <a href=\"https://ohai.social/tags/funny\" class=\"mention hashtag\" rel=\"tag\">#<span>funny</span></a></p>",
      "url": "https://ohai.social/@cookie_mumbles",
      "avatar": "https://files.ohai.social/accounts/avatars/109/380/999/955/395/974/original/c814d08a32d2a639.png",
      "avatar_static": "https://files.ohai.social/accounts/avatars/109/380/999/955/395/974/original/c814d08a32d2a639.png",
      "header": "https://files.ohai.social/accounts/headers/109/380/999/955/395/974/original/9c502235dd1c0795.jpeg",
      "header_static": "https://files.ohai.social/accounts/headers/109/380/999/955/395/974/original/9c502235dd1c0795.jpeg",
      "followers_count": 355,
      "following_count": 284,
      "statuses_count": 566,
      "last_status_at": "2022-12-07",
      "noindex": false,
      "emojis": [],
      "role": null,
      "fields": []
    },
    "media_attachments": [],
    "mentions": [],
    "tags": [],
    "emojis": [],
    "card": null,
    "poll": null
  },
  {
    "id": "109447955769349950",
    "created_at": "2022-12-03T04:54:30.412Z",
    "in_reply_to_id": null,
    "in_reply_to_account_id": null,
    "sensitive": false,
    "spoiler_text": "",
    "visibility": "public",
    "language": "en",
    "uri": "https://beige.party/users/professorkiosk/statuses/109447955769349950",
    "url": "https://beige.party/@professorkiosk/109447955769349950",
    "replies_count": 0,
    "reblogs_count": 5,
    "favourites_count": 11,
    "edited_at": "2022-12-05T02:00:09.558Z",
    "content": "<p>me: tripping on acid is crazy</p><p>my therapist:</p>",
    "reblog": null,
    "application": {
      "name": "Mastodon for iOS",
      "website": "https://app.joinmastodon.org/ios"
    },
    "account": {
      "id": "109348062348732026",
      "username": "professorkiosk",
      "acct": "professorkiosk",
      "display_name": "Professor Kiosk :bc:",
      "locked": false,
      "bot": false,
      "discoverable": true,
      "group": false,
      "created_at": "2022-11-15T00:00:00.000Z",
      "note": "<p>🏳️‍🌈 He / Him 😋 Twitter refugee 💥 If you want my professional opinion, you’re crazy 👉 More random stuff: <a href=\"http://www.justmytoots.com/professorkiosk@beige.party\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"><span class=\"invisible\">http://www.</span><span class=\"ellipsis\">justmytoots.com/professorkiosk</span><span class=\"invisible\">@beige.party</span></a></p>",
      "url": "https://beige.party/@professorkiosk",
      "avatar": "https://media.beige.party/accounts/avatars/109/348/062/348/732/026/original/d95af2bf43ad2337.png",
      "avatar_static": "https://media.beige.party/accounts/avatars/109/348/062/348/732/026/original/d95af2bf43ad2337.png",
      "header": "https://media.beige.party/accounts/headers/109/348/062/348/732/026/original/7922b66ee77780b8.jpeg",
      "header_static": "https://media.beige.party/accounts/headers/109/348/062/348/732/026/original/7922b66ee77780b8.jpeg",
      "followers_count": 616,
      "following_count": 313,
      "statuses_count": 2300,
      "last_status_at": "2022-12-08",
      "noindex": false,
      "emojis": [
        {
          "shortcode": "bc",
          "url": "https://media.beige.party/custom_emojis/images/000/005/508/original/d624e50d6662217c.png",
          "static_url": "https://media.beige.party/custom_emojis/images/000/005/508/static/d624e50d6662217c.png",
          "visible_in_picker": false
        }
      ],
      "fields": []
    },
    "media_attachments": [
      {
        "id": "109447938633453606",
        "type": "image",
        "url": "https://media.beige.party/media_attachments/files/109/447/938/633/453/606/original/9faf3b6477cbf8b7.jpg",
        "preview_url": "https://media.beige.party/media_attachments/files/109/447/938/633/453/606/small/9faf3b6477cbf8b7.jpg",
        "remote_url": null,
        "preview_remote_url": null,
        "text_url": null,
        "meta": {
          "original": {
            "width": 1200,
            "height": 755,
            "size": "1200x755",
            "aspect": 1.5894039735099337
          },
          "small": {
            "width": 504,
            "height": 317,
            "size": "504x317",
            "aspect": 1.5899053627760253
          }
        },
        "description": "Picture of the white mare from Feherlofia, Son of the White Mare (1981), a psychedelic animated film. The white mare is frowning as the universe spreads out behind her. ",
        "blurhash": "UuFP]v%MDNV@I9M}RnV@xvn$kDoztRt7V@WE"
      }
    ],
    "mentions": [],
    "tags": [],
    "emojis": [],
    "card": null,
    "poll": null
  }
]

