export const test_toots = [
  {
    "id": "109472499431799134",
    "created_at": "2022-12-07T12:56:16.979Z",
    "in_reply_to_id": null,
    "in_reply_to_account_id": null,
    "sensitive": true,
    "spoiler_text": "Content Warning",
    "visibility": "public",
    "language": "en",
    "uri": "https://ohai.social/users/cookie_mumbles/statuses/109472499431799134",
    "url": "https://ohai.social/@cookie_mumbles/109472499431799134",
    "replies_count": 0,
    "reblogs_count": 1,
    "favourites_count": 3,
    "edited_at": null,
    "content": "<p>CONTENT</p><p>(told ya)</p>",
    "reblog": null,
    "application": null,
    "account": {
      "id": "109380999955395974",
      "username": "cookie_mumbles",
      "acct": "cookie_mumbles",
      "display_name": "Cookie Mumbles",
      "locked": false,
      "bot": false,
      "discoverable": false,
      "group": false,
      "created_at": "2022-11-21T00:00:00.000Z",
      "note": "<p>Friendly cis cookie on a quest to make you chuckle</p><p>My toots -&gt; <a href=\"https://justmytoots.com/cookie_mumbles@ohai.social\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"><span class=\"invisible\">https://</span><span class=\"ellipsis\">justmytoots.com/cookie_mumbles</span><span class=\"invisible\">@ohai.social</span></a></p><p>best-of etc on twitter -&gt; <a href=\"https://linktr.ee/cookie_mumbles\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"><span class=\"invisible\">https://</span><span class=\"\">linktr.ee/cookie_mumbles</span><span class=\"invisible\"></span></a></p><p><a href=\"https://ohai.social/tags/fedi22\" class=\"mention hashtag\" rel=\"tag\">#<span>fedi22</span></a><br /><a href=\"https://ohai.social/tags/jokes\" class=\"mention hashtag\" rel=\"tag\">#<span>jokes</span></a> <a href=\"https://ohai.social/tags/fun\" class=\"mention hashtag\" rel=\"tag\">#<span>fun</span></a> <a href=\"https://ohai.social/tags/nobot\" class=\"mention hashtag\" rel=\"tag\">#<span>nobot</span></a> <a href=\"https://ohai.social/tags/joke\" class=\"mention hashtag\" rel=\"tag\">#<span>joke</span></a> <a href=\"https://ohai.social/tags/humor\" class=\"mention hashtag\" rel=\"tag\">#<span>humor</span></a> <a href=\"https://ohai.social/tags/trending\" class=\"mention hashtag\" rel=\"tag\">#<span>trending</span></a> <a href=\"https://ohai.social/tags/funny\" class=\"mention hashtag\" rel=\"tag\">#<span>funny</span></a></p>",
      "url": "https://ohai.social/@cookie_mumbles",
      "avatar": "https://files.ohai.social/accounts/avatars/109/380/999/955/395/974/original/c814d08a32d2a639.png",
      "avatar_static": "https://files.ohai.social/accounts/avatars/109/380/999/955/395/974/original/c814d08a32d2a639.png",
      "header": "https://files.ohai.social/accounts/headers/109/380/999/955/395/974/original/9c502235dd1c0795.jpeg",
      "header_static": "https://files.ohai.social/accounts/headers/109/380/999/955/395/974/original/9c502235dd1c0795.jpeg",
      "followers_count": 355,
      "following_count": 284,
      "statuses_count": 566,
      "last_status_at": "2022-12-07",
      "noindex": false,
      "emojis": [],
      "role": null,
      "fields": []
    },
    "media_attachments": [],
    "mentions": [],
    "tags": [],
    "emojis": [],
    "card": null,
    "poll": null
  },
  {
    "id": "109463245078881912",
    "created_at": "2022-12-05T21:42:46.756Z",
    "in_reply_to_id": null,
    "in_reply_to_account_id": null,
    "sensitive": false,
    "spoiler_text": "",
    "visibility": "public",
    "language": "en",
    "uri": "https://ohai.social/users/cookie_mumbles/statuses/109463245078881912",
    "url": "https://ohai.social/@cookie_mumbles/109463245078881912",
    "replies_count": 0,
    "reblogs_count": 2,
    "favourites_count": 2,
    "edited_at": null,
    "content": "<p>Shady figure: hey pssst! Wanna *opens coat revealing assortment of coke cans* Taste the Feeling?</p>",
    "reblog": null,
    "application": {
      "name": "Metatext",
      "website": "https://metabolist.org/metatext"
    },
    "account": {
      "id": "109380999955395974",
      "username": "cookie_mumbles",
      "acct": "cookie_mumbles",
      "display_name": "Cookie Mumbles",
      "locked": false,
      "bot": false,
      "discoverable": false,
      "group": false,
      "created_at": "2022-11-21T00:00:00.000Z",
      "note": "<p>Friendly cis cookie on a quest to make you chuckle</p><p>My toots -&gt; <a href=\"https://justmytoots.com/cookie_mumbles@ohai.social\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"><span class=\"invisible\">https://</span><span class=\"ellipsis\">justmytoots.com/cookie_mumbles</span><span class=\"invisible\">@ohai.social</span></a></p><p>best-of etc on twitter -&gt; <a href=\"https://linktr.ee/cookie_mumbles\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"><span class=\"invisible\">https://</span><span class=\"\">linktr.ee/cookie_mumbles</span><span class=\"invisible\"></span></a></p><p><a href=\"https://ohai.social/tags/fedi22\" class=\"mention hashtag\" rel=\"tag\">#<span>fedi22</span></a><br /><a href=\"https://ohai.social/tags/jokes\" class=\"mention hashtag\" rel=\"tag\">#<span>jokes</span></a> <a href=\"https://ohai.social/tags/fun\" class=\"mention hashtag\" rel=\"tag\">#<span>fun</span></a> <a href=\"https://ohai.social/tags/nobot\" class=\"mention hashtag\" rel=\"tag\">#<span>nobot</span></a> <a href=\"https://ohai.social/tags/joke\" class=\"mention hashtag\" rel=\"tag\">#<span>joke</span></a> <a href=\"https://ohai.social/tags/humor\" class=\"mention hashtag\" rel=\"tag\">#<span>humor</span></a> <a href=\"https://ohai.social/tags/trending\" class=\"mention hashtag\" rel=\"tag\">#<span>trending</span></a> <a href=\"https://ohai.social/tags/funny\" class=\"mention hashtag\" rel=\"tag\">#<span>funny</span></a></p>",
      "url": "https://ohai.social/@cookie_mumbles",
      "avatar": "https://files.ohai.social/accounts/avatars/109/380/999/955/395/974/original/c814d08a32d2a639.png",
      "avatar_static": "https://files.ohai.social/accounts/avatars/109/380/999/955/395/974/original/c814d08a32d2a639.png",
      "header": "https://files.ohai.social/accounts/headers/109/380/999/955/395/974/original/9c502235dd1c0795.jpeg",
      "header_static": "https://files.ohai.social/accounts/headers/109/380/999/955/395/974/original/9c502235dd1c0795.jpeg",
      "followers_count": 355,
      "following_count": 284,
      "statuses_count": 566,
      "last_status_at": "2022-12-07",
      "noindex": false,
      "emojis": [],
      "role": null,
      "fields": []
    },
    "media_attachments": [],
    "mentions": [],
    "tags": [],
    "emojis": [],
    "card": null,
    "poll": null
  }
]

